### ISSUE TITLE
"The script will never generate a response" failures on Cloudflare Worker's runtime

### ISSUE THREAD

**Issue by j-white** [najamelan/ws_stream_wasm#14]
I'm trying to use the library in a [Cloudflare Worker](https://developers.cloudflare.com/workers/runtime-apis/webassembly/rust/#3-write-your-worker-code):

Here's the call I'm making:
```
let (_ws, wsio) = WsMeta::connect( my_target, vec![ "my-proxy" ] ).await
    .expect_throw( "Failed to connect to target." );
```

The runtime fails with this exception when the line is present:
```
workerd/server/server.c++:2838: error: Uncaught exception: workerd/io/io-context.c++:1281: failed: remote.jsg.Error: The script will never generate a response.
```

It's likely Cloudflare specific, but any ideas on how this could happen? Maybe something in Pharos that's not compatible with their [request aware event-loop](https://zuplo.com/blog/2022/03/04/the-script-will-never-generate-a-response#a-request-aware-event-loop)?

**Comment by najamelan** [comment]
IIRC you can only use websockets on the main thread. I might be wrong, but have a look into that.

**Comment by j-white** [comment]
Yeah, I'm seeing similar messages with other libraries too. So not something specific to this projects.

Thanks for the quick reply!
