### ISSUE TITLE
passing headers on connect

### ISSUE THREAD

**Issue by databasedav** [najamelan/ws_stream_wasm#6]
`WsMeta::connect` takes `url` and `protocols`, how do we pass headers?

**Comment by najamelan** [comment]
Hi, which headers are we talking about? This is a TCP connection with websocket on top. See the [MDN documentation of the Js API this wraps](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket). It does not take headers.

**Comment by databasedav** [comment]
oof, all the websocket clients i've used in the past have allowed specifying headers, but this is the first time i'm working in the browser and didn't realize the web API was so basic, it looks like simply passing the authorization header in the `protocols` is a common workaround to this

thanks
