### ISSUE TITLE
Is this crate compatible with Android and iOS?

### ISSUE THREAD

**Issue by tlietz** [najamelan/ws_stream_wasm#8]
If that is not known, I will try it out soon and report back.

**Comment by najamelan** [comment]
Hi, it should work in at least modern browsers like Chrome, Firefox, Safari and Edge. It will depend on what browser you use I suppose. I imagine that the mobile versions of those browsers have the same wasm implementation as the desktop versions. Let me know if you run into issues and I will look into it.
